# Example configuration file for auto file organizer

source_folder: /path/to/your/source/folder

file_types:
  .pdf: Documents
  .docx: Documents
  .txt: Text
  .png: Images
  .jpg: Images
  .zip: Archives
  .mp3: Audio
  .xlsx: Spreadsheets
