source_folder: C:/Users/Justinboyd/Downloads

file_types:
  .pdf: Documents
  .docx: Documents
  .txt: Text
  .png: Images
  .jpg: Images
  .zip: Archives
  .mp3: Audio
  .xlsx: Spreadsheets
